# Dependencies
markdown:	kramdown
# Permalinks
permalink:	/blog/:title

# Setup
title:            Luisa
tagline:          'blog'
description:      'My personal blog.'
url:              http://ldipierr.github.io
baseurl:          
commentsystem:    google
disqus:           example

author:
  name:           Luisa Landert
  url:            

paginate:         5

# Custom vars
icon:             /assets/images/logo_test.png
cover:            /assets/images/cover_2.jpg

social:
  - icon:         twitter
    url:          
    desc:         Follow me on twitter

  - icon:         github
    url:          
    desc:         Fork me on github

  - icon:         googleplus-alt
    url:          
    desc:         Add me on google+

  - icon:         feed
    url:          
    desc:         Subscribe to my feed

menu:
  - title:        Home
    url:          /

  - title:        About
    url:          /about

copyright:
  author:         Camporez
  url:            http://camporez.github.io
  type_title:     Some rights reserved
  type_url:       http://creativecommons.org/licenses/by-nc/2.5

parallax:         false

# Google Analytics (add the UA Code, e.g.: UA-xxxxxxxx-1)
google_analytics:  

# Default Theme Color for Chrome on Android Lollipop (Use RGB ColorCode without `#`, e.g.: `db5945`)
theme_color:       7E9576
